version: '3.8'

services:
  postgres-db1:
    image: postgres:16
    container_name: postgres-db1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_HOST}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - postgres-net

  pgadmin:
    container_name: pgadmin-container  # ← igual que en tu docker run
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - postgres-net
    depends_on:
      - postgres-db1

volumes:
  postgres_data:

networks:
  postgres-net:
    driver: bridge